package wisp.utils

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Hero(
    val id: Int,
    val name: String,
    @SerialName("full_name") val fullName: String,
    @SerialName("media_name") val mediaName: String,
    @SerialName("localized_name") val localizedName: String,
    @SerialName("real_name") val realName: String,
    val aliases: String,
    val roles: String,
    @SerialName("role_levels") val roleLevels: String,
    val hype: String,
    val bio: String,
    val image: String,
    val icon: String,
    val portrait: String,
    val color: String,
    val legs: Int,
    val team: String,
    @SerialName("base_health_regen") val baseHealthRegen: Double? = null,
    @SerialName("base_mana_regen") val baseManaRegen: Double,
    @SerialName("base_movement") val baseMovement: Int,
    @SerialName("base_attack_speed") val baseAttackSpeed: Int,
    @SerialName("turn_rate") val turnRate: Double,
    @SerialName("base_armor") val baseArmor: Double,
    @SerialName("attack_range") val attackRange: Int,
    @SerialName("attack_projectile_speed") val attackProjectileSpeed: Int,
    @SerialName("attack_damage_min") val attackDamageMin: Int,
    @SerialName("attack_damage_max") val attackDamageMax: Int,
    @SerialName("attack_rate") val attackRate: Double,
    @SerialName("attack_point") val attackPoint: Double,
    @SerialName("attr_primary") val attrPrimary: String,
    @SerialName("attr_strength_base") val attrStrengthBase: Int,
    @SerialName("attr_strength_gain") val attrStrengthGain: Double,
    @SerialName("attr_intelligence_base") val attrIntelligenceBase: Int,
    @SerialName("attr_intelligence_gain") val attrIntelligenceGain: Double,
    @SerialName("attr_agility_base") val attrAgilityBase: Int,
    @SerialName("attr_agility_gain") val attrAgilityGain: Double,
    @SerialName("vision_day") val visionDay: Int,
    @SerialName("vision_night") val visionNight: Int,
    @SerialName("magic_resistance") val magicResistance: Int,
    @SerialName("is_melee") val isMelee: Int,
    val material: String? = null,
    @SerialName("json_data") val jsonData: String,
)
